name: resq_link

description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  logger: ^2.0.2
  google_fonts: ^6.1.0
  lottie: ^2.7.0
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  path: ^1.8.0  # Added path package
  shared_preferences: ^2.2.2
  location: ^5.0.3
  provider: ^6.1.4
  url_launcher: ^6.3.1
  geolocator: ^9.0.1
  permission_handler: ^11.4.0
  firebase_core: ^2.27.0
  firebase_auth: ^4.19.2
  cloud_firestore: ^4.17.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/emergency_contacts.json
